// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "ui.h"

#define TAG "ui"

