// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"


// 声明
LV_IMG_DECLARE(qrcode);    
// gif
LV_IMG_DECLARE(default1); 
LV_IMG_DECLARE(default2); 
LV_IMG_DECLARE(default3); 


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
